name: Arduino Library CI

on: [pull_request, push, workflow_dispatch]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: arduino/arduino-lint-action@v1.0.2
        with:
          library-manager: submit
          compliance: specification
          project-type: library
